#file: noinspection YAMLSchemaValidation
name: "gradle-task-run"
description: ""
inputs:
  shell:
    description: "The shell to use for any steps that use shells"
    default: "bash"
    required: "true"
  script:
    description: "Script to execute once Android Emulator is ready"
    example: './gradlew tests'
    required: "true"
  api_level:
    description: "Android API level"
    example: "35"
    default: "35"
    required: "true"

runs:
  using: "composite"
  steps:
    - name: Enable KVM group perms
      shell: ${{ inputs.shell }}
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Run Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ input.api_level }}
        script: ${{ input.script }}
