#file: noinspection YAMLSchemaValidation
name: "gradle-task-run"
description: ""
inputs:
  shell:
    description: "The shell to use for any steps that use shells"
    default: "bash"
    required: "true"
  script:
    description: "Script to execute once Android Emulator is ready"
    example: './gradlew tests'
    required: "true"
  api_level:
    description: "Android API level"
    example: "35"
    default: "35"
    required: "true"
  arch:
    description: "CPU architecture"
    default: "x86_64"
    required: "true"
  target:
    description: "System image target"
    default: "default"
    required: "true"

runs:
  using: "composite"
  steps:
    - name: Enable KVM group perms
      shell: ${{ inputs.shell }}
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Restore AVD cache
      id: avd-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ runner.os }}-${{ inputs.api_level }}

    - name: Cache AVD + Snapshot
      id: avd-cache-generate
      if: steps.avd-cache-restore.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level:  ${{ inputs.api_level }}
        arch: ${{ inputs.arch }}
        target: ${{ inputs.target }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: "Save Android SDK Platform Tools"
      uses: actions/cache/save@v4
      if: steps.avd-cache-generate.outputs.cache-hit == 'true'
      with:
        path: |
          /usr/local/lib/android/sdk/platform-tools
          /home/runner/.config/.android/cache
        key: avd-${{ runner.os }}-${{ inputs.api_level }}

    - name: Run Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level:  ${{ inputs.api_level }}
        arch: ${{ inputs.arch }}
        target: ${{ inputs.target }}
        script:  ${{ inputs.script }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
