# pip3 install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

site_name: AutoMobile
repo_name: AutoMobile
repo_url: https://github.com/zillow/auto-mobile
site_description: "Mobile interaction automation"
site_author: Zillow
remote_branch: gh-pages

copyright: 'Copyright &copy; 2025 Zillow Group'

theme:
  name: 'material'
  #  favicon: images/tbd.png
  #  logo: images/tbd.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Inter'
    code: 'Fira Code'
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - attr_list
  - md_in_html

nav:
  - 'Introduction': index.md
  - 'Installation': installation.md
  - 'Local Development': local-development.md
  - 'FAQ': faq.md
  - 'Features':
      - 'Overview': features.md
      - 'Batteries Included': batteries-included.md
      - 'Plan Authoring & Execution': plan-authoring-execution-options.md
      - 'CLI': cli.md
      - 'CI': ci.md
  - 'MCP Client Config':
      - 'Overview': mcp/overview.md
      - 'Firebender': mcp/firebender.md
      - 'Cursor': mcp/cursor.md
      - 'Goose': mcp/goose.md
  - 'GitHub Discussions': https://github.com/zillow/auto-mobile/discussions
  - 'Contributing': contributing.md
  - 'Change Log': changelog.md
  - 'Security': security.md

