# pip3 install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

site_name: AutoMobile
repo_name: AutoMobile
repo_url: https://github.com/zillow/auto-mobile
site_description: "Mobile interaction automation"
site_author: Zillow
remote_branch: gh-pages
use_directory_urls: true

copyright: 'Copyright &copy; 2025 Zillow Group'

plugins:
  - search
  - mermaid2:
      version: 10.0.2

theme:
  name: 'material'
  favicon: img/favicon.ico
  logo: img/auto_mobile_sticker_splash.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'green'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Inter'
    code: 'Fira Code'
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - attr_list
  - md_in_html

nav:
  - 'Overview': index.md
  - 'Installation': installation.md
  - 'Features':
      - 'Overview': features/index.md
      - 'MCP Server':
          - 'Overview': features/mcp-server/index.md
          - 'Actions': features/mcp-server/actions.md
          - 'Observation': features/mcp-server/observation.md
          - 'Interaction Loop': features/mcp-server/interaction-loop.md
      - 'Test Authoring':
          - 'Overview': features/test-authoring/index.md
          - 'Plan Syntax': features/test-authoring/plan-syntax.md
      - 'Test Execution':
          - 'Overview': features/test-execution/index.md
          - 'JUnitRunner': features/test-execution/junitrunner.md
          - 'CI': features/test-execution/ci.md
          - 'Options': features/test-execution/options.md
      - 'Batteries Included': features/batteries-included.md
      - 'CLI': features/cli.md
  - 'MCP Client Support':
      - 'Overview': mcp-clients/index.md
      - 'Firebender ': mcp-clients/firebender.md
      - 'Cursor': mcp-clients/cursor.md
      - 'Goose': mcp-clients/goose.md
  - 'Contributing':
      - 'How': contributing/index.md
      - 'Local Development': contributing/local-development.md
      - 'GitHub Discussions': https://github.com/zillow/auto-mobile/discussions
  - 'FAQ': faq.md
  - 'Security': security.md
  - 'Change Log': changelog.md
