// Database module exports
export { getDatabase, closeDatabase, getDatabasePath } from "./database";
export { runMigrations } from "./migrator";
export type {
  Database,
  DeviceConfigTable,
  PerformanceThresholdsTable,
  PerformanceThresholds,
  NewPerformanceThresholds,
  PerformanceAuditResultsTable,
  NewPerformanceAuditResult,
  NavigationAppsTable,
  NavigationApp,
  NewNavigationApp,
  NavigationNodesTable,
  NavigationNode,
  NewNavigationNode,
  NavigationEdgesTable,
  NavigationEdge,
  NewNavigationEdge,
  UIElementsTable,
  UIElement,
  NewUIElement,
  EdgeUIElementsTable,
  NewEdgeUIElement,
  NodeModalsTable,
  NewNodeModal,
  EdgeModalsTable,
  NewEdgeModal,
  ScrollPositionsTable,
  NewScrollPosition,
  PredictionOutcomesTable,
  NewPredictionOutcome,
  PredictionTransitionStatsTable,
  PredictionTransitionStats,
  NewPredictionTransitionStats,
  ToolCallsTable,
  ToolCall,
  NewToolCall,
  FeatureFlagsTable,
  DeviceSnapshotsTable,
  DeviceSnapshot,
  NewDeviceSnapshot,
  DeviceSnapshotUpdate,
  DeviceSnapshotConfigsTable,
  VideoRecordingsTable,
  VideoRecording,
  NewVideoRecording,
  VideoRecordingUpdate,
  VideoRecordingConfigsTable,
  AppearanceConfigsTable,
} from "./types";
