#file: noinspection YAMLSchemaValidation
name: "npm-task-run"
description: ""
inputs:
  shell:
    description: "The shell to use for any steps that use shells"
    default: "bash"
    required: "true"

runs:
  using: "composite"
  steps:
    - name: "Setup Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"

    - name: "Cache NPM Dependencies"
      shell: ${{ inputs.shell }}
      run: |
        npm ci --cache .npm --prefer-offline

    - name: "Build AutoMobile"
      shell: ${{ inputs.shell }}
      run: |
        npm run build

    - name: "Globally Install AutoMobile"
      shell: ${{ inputs.shell }}
      run: |
        npm install -g .
