#!/usr/bin/env bash
#
# AutoMobile Android hot-reload development workflow.
#
# This is the main entry point for Android development. It combines APK building,
# hot-reload watching, MCP server management, and AI coding assistant integration.
#
# Usage:
#   ./scripts/local-dev/android-hot-reload.sh [options]
#
# Options:
#   --device <id>        Target specific ADB device
#   --skip-ai            Skip AI agent prompt (still runs APK watcher + MCP server)
#   --once               Build/install once and exit (no MCP server, no watch loop)
#   --update-checksum    Update release.ts with APK checksum
#   --poll-interval <s>  File watch interval (default: 2)
#   --help               Show help
#
# Default behavior: APK build/watch + MCP server + AI agent prompt
# With --skip-ai: APK build/watch + MCP server (no AI prompt)
# With --once: Build/install once and exit
#
# Environment:
#   ANDROID_SERIAL       ADB device id override
#   AUTOMOBILE_PORT      Override MCP dev server port
#   AUTO_MOBILE_PORT     Deprecated alias for AUTOMOBILE_PORT
#   AI_YOLO_MODE         If set, launch Claude/Codex with auto-accept flags

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Source library files
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/deps.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/adb.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/apk.sh"

# Path constants
ANDROID_DIR="${PROJECT_ROOT}/android"
SERVICE_DIR="${ANDROID_DIR}/accessibility-service"
APK_PATH="${SERVICE_DIR}/build/outputs/apk/debug/accessibility-service-debug.apk"
MCP_JSON="${PROJECT_ROOT}/.mcp.json"
CODEX_CONFIG_DIR="${HOME}/.codex"
CODEX_TOML="${CODEX_CONFIG_DIR}/config.toml"
PID_FILE="${PROJECT_ROOT}/.automobile-hot-reload.pid"

# CLI options with defaults
DEVICE_ID=""
SKIP_AI=false
RUN_ONCE=false
UPDATE_CHECKSUM=false
POLL_INTERVAL=2

# Runtime state
MCP_PID=""
WATCHER_PID=""

usage() {
  cat << EOF
Usage: $0 [options]

AutoMobile Android hot-reload development workflow.

Options:
  --device <id>        Target specific ADB device
  --skip-ai            Skip AI agent prompt (still runs APK watcher + MCP server)
  --once               Build/install once and exit (no MCP server, no watch loop)
  --update-checksum    Update release.ts with APK checksum
  --poll-interval <s>  File watch interval (default: 2)
  --help               Show this help text

Default behavior: APK build/watch + MCP server + AI agent prompt
With --skip-ai: APK build/watch + MCP server (no AI prompt)
With --once: Build/install once and exit

Environment variables:
  ANDROID_SERIAL       ADB device id override
  AUTOMOBILE_PORT      Override MCP dev server port
  AI_YOLO_MODE         If set, launch Claude/Codex with auto-accept flags
EOF
}

# Kill any previous hot-reload processes
kill_previous() {
  if [[ -f "${PID_FILE}" ]]; then
    local old_pid
    old_pid=$(cat "${PID_FILE}" 2>/dev/null || true)
    if [[ -n "${old_pid}" ]] && kill -0 "${old_pid}" 2>/dev/null; then
      log_info "Killing previous hot-reload process (PID ${old_pid})..."
      kill "${old_pid}" 2>/dev/null || true
      # Give it a moment to clean up
      sleep 1
      # Force kill if still running
      if kill -0 "${old_pid}" 2>/dev/null; then
        kill -9 "${old_pid}" 2>/dev/null || true
      fi
    fi
    rm -f "${PID_FILE}"
  fi

  # Also kill any orphaned processes
  local pids
  pids=$(pgrep -f "android-hot-reload.sh" 2>/dev/null | grep -v "$$" || true)
  if [[ -n "${pids}" ]]; then
    log_info "Killing orphaned hot-reload processes..."
    echo "${pids}" | xargs kill 2>/dev/null || true
  fi
}

# Update .mcp.json for local HTTP development
update_mcp_json() {
  local port="$1"
  local url="http://localhost:${port}/auto-mobile/streamable"

  log_info "Updating ${MCP_JSON} for local development..."
  log_info "MCP endpoint: ${url}"

  cat > "${MCP_JSON}" << EOF
{
  "mcpServers": {
    "auto-mobile": {
      "type": "http",
      "url": "${url}",
      "env": {
        "AUTOMOBILE_DEBUG": "1",
        "AUTOMOBILE_DEBUG_PERF": "1"
      }
    }
  }
}
EOF
}

# Update ~/.codex/config.toml for local HTTP development
update_codex_toml() {
  local port="$1"
  local url="http://localhost:${port}/auto-mobile/streamable"

  log_info "Updating ${CODEX_TOML} for local development..."

  # Ensure the config directory exists
  mkdir -p "${CODEX_CONFIG_DIR}"

  cat > "${CODEX_TOML}" << EOF
# Codex configuration for AutoMobile development
# Auto-generated by android-hot-reload.sh

[mcp_servers.auto-mobile]
type = "http"
url = "${url}"
EOF
}

# Start MCP dev server in background
start_mcp_server() {
  export AUTOMOBILE_ACCESSIBILITY_APK_PATH="${APK_PATH}"
  export AUTOMOBILE_DEBUG=1
  export AUTOMOBILE_DEBUG_PERF=1
  log_info "Starting MCP dev server in background..."
  nohup bun run dev > "${PROJECT_ROOT}/scratch/mcp-server.log" 2>&1 &
  MCP_PID=$!
  log_info "MCP server started (PID ${MCP_PID})"
  log_info "Logs: ${PROJECT_ROOT}/scratch/mcp-server.log"
}

# Start APK watcher in background
start_apk_watcher() {
  log_info "Starting APK watcher in background..."
  # Run watch_loop in a subshell in background, redirect output to log file
  (watch_loop "${POLL_INTERVAL}" "${UPDATE_CHECKSUM}") >> "${PROJECT_ROOT}/scratch/hot-reload.log" 2>&1 &
  WATCHER_PID=$!
  echo "${WATCHER_PID}" > "${PID_FILE}"
  log_info "APK watcher started (PID ${WATCHER_PID})"
  log_info "Logs: ${PROJECT_ROOT}/scratch/hot-reload.log"
}

# Prompt user to select an AI coding assistant
prompt_ide() {
  if ! ensure_gum; then
    log_warn "Skipping IDE prompt (gum not available)."
    return
  fi

  # Clear terminal for clean prompt
  clear

  local choice
  choice=$(gum choose --header "Start an AI coding assistant?" "Claude Code" "Codex" "Neither")

  case "${choice}" in
    "Claude Code")
      log_info "Starting Claude Code..."
      if [[ -n "${AI_YOLO_MODE:-}" ]]; then
        log_info "AI_YOLO_MODE enabled - using --dangerously-skip-permissions"
        exec claude --dangerously-skip-permissions
      else
        exec claude
      fi
      ;;
    "Codex")
      log_info "Starting Codex..."
      if [[ -n "${AI_YOLO_MODE:-}" ]]; then
        log_info "AI_YOLO_MODE enabled - using --full-auto"
        exec codex --full-auto
      else
        exec codex
      fi
      ;;
    "Neither")
      log_info "Hot-reload running in background. Use 'tail -f scratch/hot-reload.log' to monitor."
      ;;
  esac
}

# Cleanup on exit
cleanup() {
  if [[ -n "${MCP_PID}" ]]; then
    log_info "Stopping MCP dev server (PID ${MCP_PID})..."
    kill "${MCP_PID}" 2>/dev/null || true
    wait "${MCP_PID}" 2>/dev/null || true
  fi
  if [[ -n "${WATCHER_PID}" ]]; then
    log_info "Stopping APK watcher (PID ${WATCHER_PID})..."
    kill "${WATCHER_PID}" 2>/dev/null || true
    wait "${WATCHER_PID}" 2>/dev/null || true
  fi
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --device)
      if [[ $# -lt 2 ]]; then
        log_error "--device requires a value."
        usage
        exit 1
      fi
      DEVICE_ID="$2"
      shift 2
      ;;
    --skip-ai)
      SKIP_AI=true
      shift
      ;;
    --once)
      RUN_ONCE=true
      shift
      ;;
    --update-checksum)
      UPDATE_CHECKSUM=true
      shift
      ;;
    --poll-interval)
      if [[ $# -lt 2 ]]; then
        log_error "--poll-interval requires a value."
        usage
        exit 1
      fi
      POLL_INTERVAL="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

# Set up cleanup trap
trap cleanup EXIT INT TERM

# Ensure scratch directory exists
mkdir -p "${PROJECT_ROOT}/scratch"

# Check and install dependencies (gum, node, bun)
if ! ensure_dependencies; then
  log_error "Dependency check failed. Exiting."
  exit 1
fi

# Resolve ADB
resolve_adb

# Device resolution is optional - we can still build without a device
HAVE_DEVICE=false
if resolve_device; then
  HAVE_DEVICE=true
fi

if [[ -n "${DEVICE_ID}" ]]; then
  log_info "Target device: ${DEVICE_ID}"
elif [[ "${HAVE_DEVICE}" == "true" ]]; then
  log_info "Target: all connected devices"
else
  log_info "Target: no devices (will install when available)"
fi
log_info "APK path: ${APK_PATH}"
log_info "Gradle: ${ANDROID_DIR}/gradlew :accessibility-service:assembleDebug"

# Build APK
if ! build_apk; then
  log_error "Initial build failed. Fix errors and retry."
  exit 1
fi

# Install if devices available
if [[ "${HAVE_DEVICE}" == "true" ]]; then
  if ! install_apk; then
    log_warn "Initial install failed. Will retry when devices connect."
  fi
else
  log_info "No devices connected. APK built and ready for install."
fi

# Handle --once mode: build/install and exit
if [[ "${RUN_ONCE}" == "true" ]]; then
  checksum="$(compute_checksum)"
  if [[ -n "${checksum}" ]]; then
    log_info "APK sha256: ${checksum}"
    if [[ "${UPDATE_CHECKSUM}" == "true" ]]; then
      update_checksum "${checksum}"
    fi
  fi
  log_info "Run-once mode complete."
  exit 0
fi

# Kill previous processes and set up new run
kill_previous

PORT=$(detect_port "${PROJECT_ROOT}")
log_info "Using port ${PORT}"

update_mcp_json "${PORT}"
update_codex_toml "${PORT}"

# Change to project root for bun commands
cd "${PROJECT_ROOT}"

# Start MCP server
start_mcp_server

# Start APK watcher (runs in foreground if --skip-ai, background otherwise)
if [[ "${SKIP_AI}" == "true" ]]; then
  log_info "Hot-reload running."
  log_info "MCP endpoint: http://localhost:${PORT}/auto-mobile/streamable"
  # Run watch loop in foreground
  watch_loop "${POLL_INTERVAL}" "${UPDATE_CHECKSUM}"
else
  # Start watcher in background and prompt for IDE
  start_apk_watcher
  # Give processes a moment to start
  sleep 2
  prompt_ide
fi
