#!/usr/bin/env bash
#
# AutoMobile iOS XCTestService hot-reload development workflow.
#
# Usage:
#   ./scripts/local-dev/ios-hot-reload.sh [options]
#
# Options:
#   --device <udid>      Target a specific booted simulator
#   --skip-ai            Skip AI agent prompt (still runs watcher + MCP server)
#   --once               Build once and exit (no MCP server, no watch loop)
#   --poll-interval <s>  File watch interval (default: 2)
#   --help               Show help
#
# Default behavior: build/watch + MCP server + AI agent prompt
# With --skip-ai: build/watch + MCP server (no AI prompt)
# With --once: build once and exit
#
# Environment:
#   AUTOMOBILE_PORT      Override MCP dev server port
#   AUTO_MOBILE_PORT     Deprecated alias for AUTOMOBILE_PORT
#   AI_YOLO_MODE         If set, launch Claude/Codex with auto-accept flags
#   XCTESTSERVICE_PORT   Override XCTestService port (default: 8765)
#   XCTESTSERVICE_BUNDLE_ID   Target app bundle ID (optional)
#   XCTESTSERVICE_TIMEOUT     Server timeout in seconds (optional)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Source library files
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/deps.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/xctestservice.sh"

# Path constants
XCTEST_SERVICE_DIR="${PROJECT_ROOT}/ios/XCTestService"
DERIVED_DATA_PATH="/tmp/automobile-xctestservice"
MCP_JSON="${PROJECT_ROOT}/.mcp.json"
CODEX_CONFIG_DIR="${HOME}/.codex"
CODEX_TOML="${CODEX_CONFIG_DIR}/config.toml"
PID_FILE="${PROJECT_ROOT}/.automobile-hot-reload.pid"

# CLI options with defaults
DEVICE_ID=""
SKIP_AI=false
RUN_ONCE=false
POLL_INTERVAL=2

# Runtime state (TS_WATCHER_PID set in start_ts_watcher)
TS_WATCHER_PID=""
WATCHER_PID=""

usage() {
  cat << EOF
Usage: $0 [options]

AutoMobile iOS XCTestService hot-reload development workflow.

Options:
  --device <udid>      Target a specific booted simulator
  --skip-ai            Skip AI agent prompt (still runs watcher + MCP server)
  --once               Build once and exit (no MCP server, no watch loop)
  --poll-interval <s>  File watch interval (default: 2)
  --help               Show this help text

Default behavior: build/watch + MCP server + AI agent prompt
With --skip-ai: build/watch + MCP server (no AI prompt)
With --once: build once and exit

Environment variables:
  AUTOMOBILE_PORT          Override MCP dev server port
  AI_YOLO_MODE             If set, launch Claude/Codex with auto-accept flags
  XCTESTSERVICE_PORT       Override XCTestService port (default: 8765)
  XCTESTSERVICE_BUNDLE_ID  Target app bundle ID (optional)
  XCTESTSERVICE_TIMEOUT    Server timeout in seconds (optional)
EOF
}

# Kill any previous hot-reload processes
kill_previous() {
  if [[ -f "${PID_FILE}" ]]; then
    local old_pid
    old_pid=$(cat "${PID_FILE}" 2>/dev/null || true)
    if [[ -n "${old_pid}" ]] && kill -0 "${old_pid}" 2>/dev/null; then
      log_info "Killing previous hot-reload process (PID ${old_pid})..."
      kill "${old_pid}" 2>/dev/null || true
      sleep 1
      if kill -0 "${old_pid}" 2>/dev/null; then
        kill -9 "${old_pid}" 2>/dev/null || true
      fi
    fi
    rm -f "${PID_FILE}"
  fi

  local pids
  pids=$(pgrep -f "ios-hot-reload.sh" 2>/dev/null | grep -v "$$" || true)
  if [[ -n "${pids}" ]]; then
    log_info "Killing orphaned hot-reload processes..."
    echo "${pids}" | xargs kill 2>/dev/null || true
  fi
}

# Update .mcp.json for local stdio development
update_mcp_json() {
  log_info "Updating ${MCP_JSON} for local development..."

  cat > "${MCP_JSON}" << EOF
{
  "mcpServers": {
    "auto-mobile": {
      "command": "npx",
      "args": [
        "-y",
        "@kaeawc/auto-mobile",
        "--debug",
        "--debug-perf"
      ]
    }
  }
}
EOF
}

# Update ~/.codex/config.toml for local stdio development
update_codex_toml() {
  log_info "Updating ${CODEX_TOML} for local development..."

  mkdir -p "${CODEX_CONFIG_DIR}"

  cat > "${CODEX_TOML}" << EOF
# Codex configuration for AutoMobile development
# Auto-generated by ios-hot-reload.sh

[mcp_servers.auto-mobile]
command = "npx"
args = ["-y", "@kaeawc/auto-mobile", "--debug", "--debug-perf"]
EOF
}

# Reload MCP daemon by restarting the daemon process
# The daemon is identified by the --daemon-mode flag
reload_mcp_daemon() {
  log_info "Restarting MCP daemon..."
  # Use auto-mobile CLI to restart the daemon gracefully
  if command -v auto-mobile >/dev/null 2>&1; then
    auto-mobile --daemon restart --debug --debug-perf 2>&1 | while read -r line; do
      log_info "[daemon] ${line}"
    done
  else
    # Fallback: kill daemon processes directly
    local pids
    pids=$(pgrep -f "auto-mobile.*--daemon-mode" 2>/dev/null || true)
    if [[ -n "${pids}" ]]; then
      log_info "Killing daemon processes: ${pids}"
      echo "${pids}" | xargs kill 2>/dev/null || true
    fi
  fi
}

# List TypeScript source files to watch
list_ts_files() {
  local src_dir="${PROJECT_ROOT}/src"
  if [[ -d "${src_dir}" ]]; then
    find "${src_dir}" -type f -name "*.ts" 2>/dev/null || true
  fi
}

# Compute hash of TypeScript file timestamps
hash_ts_state() {
  list_ts_files | while read -r file; do
    if [[ -f "${file}" ]]; then
      if [[ "$(uname -s)" == "Darwin" ]]; then
        stat -f "%m %N" "${file}" 2>/dev/null || true
      else
        stat -c "%Y %n" "${file}" 2>/dev/null || true
      fi
    fi
  done | sort | hash_stream
}

# Build TypeScript before daemon restart
build_typescript() {
  log_info "Building TypeScript..."
  if (cd "${PROJECT_ROOT}" && bun run build); then
    log_info "TypeScript build complete."
    return 0
  else
    log_warn "TypeScript build failed."
    return 1
  fi
}

# Watch TypeScript files and reload daemon on changes
watch_ts_loop() {
  local poll_interval="${1:-2}"
  local last_ts_hash
  last_ts_hash="$(hash_ts_state)"

  while true; do
    sleep "${poll_interval}"

    local next_ts_hash
    next_ts_hash="$(hash_ts_state)"
    if [[ "${next_ts_hash}" != "${last_ts_hash}" ]]; then
      log_info "TypeScript change detected. Rebuilding and reloading MCP daemon..."
      if build_typescript; then
        reload_mcp_daemon
      fi
      last_ts_hash="${next_ts_hash}"
    fi
  done
}

# Start watcher in background
start_watcher() {
  log_info "Starting XCTestService watcher in background..."
  (watch_loop "${POLL_INTERVAL}") >> "${PROJECT_ROOT}/scratch/ios-hot-reload.log" 2>&1 &
  WATCHER_PID=$!
  echo "${WATCHER_PID}" > "${PID_FILE}"
  log_info "Watcher started (PID ${WATCHER_PID})"
  log_info "Logs: ${PROJECT_ROOT}/scratch/ios-hot-reload.log"
}

# Prompt user to select an AI coding assistant
prompt_ide() {
  if ! ensure_gum; then
    log_warn "Skipping IDE prompt (gum not available)."
    return
  fi

  clear

  local choice
  choice=$(gum choose --header "Start an AI coding assistant?" "Claude Code" "Codex" "Neither")

  # Disown background watchers before exec so they keep running
  # when the shell process is replaced
  disown_watchers() {
    if [[ -n "${TS_WATCHER_PID}" ]]; then
      disown "${TS_WATCHER_PID}" 2>/dev/null || true
    fi
    if [[ -n "${WATCHER_PID}" ]]; then
      disown "${WATCHER_PID}" 2>/dev/null || true
    fi
    # Disable cleanup trap since we want watchers to keep running
    trap - EXIT INT TERM
  }

  case "${choice}" in
    "Claude Code")
      log_info "Starting Claude Code..."
      log_info "Hot-reload watchers running in background."
      disown_watchers
      if [[ -n "${AI_YOLO_MODE:-}" ]]; then
        log_info "AI_YOLO_MODE enabled - using --dangerously-skip-permissions"
        exec claude --dangerously-skip-permissions
      else
        exec claude
      fi
      ;;
    "Codex")
      log_info "Starting Codex..."
      log_info "Hot-reload watchers running in background."
      disown_watchers
      if [[ -n "${AI_YOLO_MODE:-}" ]]; then
        log_info "AI_YOLO_MODE enabled - using --full-auto"
        exec codex --full-auto
      else
        exec codex
      fi
      ;;
    "Neither")
      log_info "Hot-reload watchers running in background."
      log_info "Use 'tail -f scratch/ios-hot-reload.log' to monitor."
      disown_watchers
      ;;
  esac
}

# Cleanup on exit
cleanup() {
  if [[ -n "${TS_WATCHER_PID}" ]]; then
    log_info "Stopping TypeScript watcher (PID ${TS_WATCHER_PID})..."
    kill "${TS_WATCHER_PID}" 2>/dev/null || true
    wait "${TS_WATCHER_PID}" 2>/dev/null || true
  fi
  if [[ -n "${WATCHER_PID}" ]]; then
    log_info "Stopping watcher (PID ${WATCHER_PID})..."
    kill "${WATCHER_PID}" 2>/dev/null || true
    wait "${WATCHER_PID}" 2>/dev/null || true
  fi
  stop_xctestservice
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --device)
      if [[ $# -lt 2 ]]; then
        log_error "--device requires a value."
        usage
        exit 1
      fi
      DEVICE_ID="$2"
      shift 2
      ;;
    --skip-ai)
      SKIP_AI=true
      shift
      ;;
    --once)
      RUN_ONCE=true
      shift
      ;;
    --poll-interval)
      if [[ $# -lt 2 ]]; then
        log_error "--poll-interval requires a value."
        usage
        exit 1
      fi
      POLL_INTERVAL="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

trap cleanup EXIT INT TERM

mkdir -p "${PROJECT_ROOT}/scratch"

if ! ensure_dependencies; then
  log_error "Dependency check failed. Exiting."
  exit 1
fi

if ! command -v xcodebuild >/dev/null 2>&1; then
  log_error "xcodebuild not found. Install Xcode."
  exit 1
fi

if [[ ! -d "${XCTEST_SERVICE_DIR}" ]]; then
  log_error "XCTestService directory not found: ${XCTEST_SERVICE_DIR}"
  exit 1
fi

if [[ -n "${DEVICE_ID}" ]]; then
  export SIMULATOR_ID_OVERRIDE="${DEVICE_ID}"
  log_info "Target simulator: ${DEVICE_ID} (must be booted)"
else
  log_info "Target: booted simulator"
fi

log_info "Derived data: ${DERIVED_DATA_PATH}"

if [[ "${RUN_ONCE}" == "true" ]]; then
  if ! build_xctestservice; then
    log_error "Build failed. Fix errors and retry."
    exit 1
  fi
  log_info "Run-once mode complete."
  exit 0
fi

kill_previous

update_mcp_json
update_codex_toml

cd "${PROJECT_ROOT}"

# Start TypeScript watcher in background
start_ts_watcher() {
  log_info "Starting TypeScript watcher in background..."
  (watch_ts_loop "${POLL_INTERVAL}") >> "${PROJECT_ROOT}/scratch/ts-hot-reload.log" 2>&1 &
  TS_WATCHER_PID=$!
  log_info "TypeScript watcher started (PID ${TS_WATCHER_PID})"
  log_info "Logs: ${PROJECT_ROOT}/scratch/ts-hot-reload.log"
}

start_ts_watcher

if [[ "${SKIP_AI}" == "true" ]]; then
  log_info "Hot-reload running."
  log_info "MCP config: ${MCP_JSON}"
  watch_loop "${POLL_INTERVAL}"
else
  start_watcher
  sleep 2
  prompt_ide
fi
