#!/usr/bin/env bash
#
# AutoMobile iOS XCTestService hot-reload development workflow.
#
# Usage:
#   ./scripts/local-dev/ios-hot-reload.sh [options]
#
# Options:
#   --device <udid>      Target a specific booted simulator
#   --skip-ai            Skip AI agent prompt (still runs watcher + MCP server)
#   --once               Build once and exit (no MCP server, no watch loop)
#   --poll-interval <s>  File watch interval (default: 2)
#   --help               Show help
#
# Default behavior: build/watch + MCP server + AI agent prompt
# With --skip-ai: build/watch + MCP server (no AI prompt)
# With --once: build once and exit
#
# Environment:
#   AUTOMOBILE_PORT      Override MCP dev server port
#   AUTO_MOBILE_PORT     Deprecated alias for AUTOMOBILE_PORT
#   AI_YOLO_MODE         If set, launch Claude/Codex with auto-accept flags
#   XCTESTSERVICE_PORT   Override XCTestService port (default: 8765)
#   XCTESTSERVICE_BUNDLE_ID   Target app bundle ID (optional)
#   XCTESTSERVICE_TIMEOUT     Server timeout in seconds (optional)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Source library files
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/deps.sh"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/xctestservice.sh"

# Path constants
XCTEST_SERVICE_DIR="${PROJECT_ROOT}/ios/XCTestService"
DERIVED_DATA_PATH="/tmp/automobile-xctestservice"
MCP_JSON="${PROJECT_ROOT}/.mcp.json"
CODEX_CONFIG_DIR="${HOME}/.codex"
CODEX_TOML="${CODEX_CONFIG_DIR}/config.toml"
PID_FILE="${PROJECT_ROOT}/.automobile-hot-reload.pid"

# CLI options with defaults
DEVICE_ID=""
SKIP_AI=false
RUN_ONCE=false
POLL_INTERVAL=2

# Runtime state
MCP_PID=""
WATCHER_PID=""

usage() {
  cat << EOF
Usage: $0 [options]

AutoMobile iOS XCTestService hot-reload development workflow.

Options:
  --device <udid>      Target a specific booted simulator
  --skip-ai            Skip AI agent prompt (still runs watcher + MCP server)
  --once               Build once and exit (no MCP server, no watch loop)
  --poll-interval <s>  File watch interval (default: 2)
  --help               Show this help text

Default behavior: build/watch + MCP server + AI agent prompt
With --skip-ai: build/watch + MCP server (no AI prompt)
With --once: build once and exit

Environment variables:
  AUTOMOBILE_PORT          Override MCP dev server port
  AI_YOLO_MODE             If set, launch Claude/Codex with auto-accept flags
  XCTESTSERVICE_PORT       Override XCTestService port (default: 8765)
  XCTESTSERVICE_BUNDLE_ID  Target app bundle ID (optional)
  XCTESTSERVICE_TIMEOUT    Server timeout in seconds (optional)
EOF
}

# Kill any previous hot-reload processes
kill_previous() {
  if [[ -f "${PID_FILE}" ]]; then
    local old_pid
    old_pid=$(cat "${PID_FILE}" 2>/dev/null || true)
    if [[ -n "${old_pid}" ]] && kill -0 "${old_pid}" 2>/dev/null; then
      log_info "Killing previous hot-reload process (PID ${old_pid})..."
      kill "${old_pid}" 2>/dev/null || true
      sleep 1
      if kill -0 "${old_pid}" 2>/dev/null; then
        kill -9 "${old_pid}" 2>/dev/null || true
      fi
    fi
    rm -f "${PID_FILE}"
  fi

  local pids
  pids=$(pgrep -f "ios-hot-reload.sh" 2>/dev/null | grep -v "$$" || true)
  if [[ -n "${pids}" ]]; then
    log_info "Killing orphaned hot-reload processes..."
    echo "${pids}" | xargs kill 2>/dev/null || true
  fi
}

# Update .mcp.json for local HTTP development
update_mcp_json() {
  local port="$1"
  local url="http://localhost:${port}/auto-mobile/streamable"

  log_info "Updating ${MCP_JSON} for local development..."
  log_info "MCP endpoint: ${url}"

  cat > "${MCP_JSON}" << EOF
{
  "mcpServers": {
    "auto-mobile": {
      "type": "http",
      "url": "${url}",
      "env": {
        "AUTOMOBILE_DEBUG": "1",
        "AUTOMOBILE_DEBUG_PERF": "1"
      }
    }
  }
}
EOF
}

# Update ~/.codex/config.toml for local HTTP development
update_codex_toml() {
  local port="$1"
  local url="http://localhost:${port}/auto-mobile/streamable"

  log_info "Updating ${CODEX_TOML} for local development..."

  mkdir -p "${CODEX_CONFIG_DIR}"

  cat > "${CODEX_TOML}" << EOF
# Codex configuration for AutoMobile development
# Auto-generated by ios-hot-reload.sh

[mcp_servers.auto-mobile]
type = "http"
url = "${url}"
EOF
}

# Start MCP dev server in background
start_mcp_server() {
  export AUTOMOBILE_DEBUG=1
  export AUTOMOBILE_DEBUG_PERF=1
  log_info "Starting MCP dev server in background..."
  nohup bun run dev > "${PROJECT_ROOT}/scratch/mcp-server.log" 2>&1 &
  MCP_PID=$!
  log_info "MCP server started (PID ${MCP_PID})"
  log_info "Logs: ${PROJECT_ROOT}/scratch/mcp-server.log"
}

# Start watcher in background
start_watcher() {
  log_info "Starting XCTestService watcher in background..."
  (watch_loop "${POLL_INTERVAL}") >> "${PROJECT_ROOT}/scratch/ios-hot-reload.log" 2>&1 &
  WATCHER_PID=$!
  echo "${WATCHER_PID}" > "${PID_FILE}"
  log_info "Watcher started (PID ${WATCHER_PID})"
  log_info "Logs: ${PROJECT_ROOT}/scratch/ios-hot-reload.log"
}

# Prompt user to select an AI coding assistant
prompt_ide() {
  if ! ensure_gum; then
    log_warn "Skipping IDE prompt (gum not available)."
    return
  fi

  clear

  local choice
  choice=$(gum choose --header "Start an AI coding assistant?" "Claude Code" "Codex" "Neither")

  case "${choice}" in
    "Claude Code")
      log_info "Starting Claude Code..."
      if [[ -n "${AI_YOLO_MODE:-}" ]]; then
        log_info "AI_YOLO_MODE enabled - using --dangerously-skip-permissions"
        exec claude --dangerously-skip-permissions
      else
        exec claude
      fi
      ;;
    "Codex")
      log_info "Starting Codex..."
      if [[ -n "${AI_YOLO_MODE:-}" ]]; then
        log_info "AI_YOLO_MODE enabled - using --full-auto"
        exec codex --full-auto
      else
        exec codex
      fi
      ;;
    "Neither")
      log_info "Hot-reload running in background. Use 'tail -f scratch/ios-hot-reload.log' to monitor."
      ;;
  esac
}

# Cleanup on exit
cleanup() {
  if [[ -n "${MCP_PID}" ]]; then
    log_info "Stopping MCP dev server (PID ${MCP_PID})..."
    kill "${MCP_PID}" 2>/dev/null || true
    wait "${MCP_PID}" 2>/dev/null || true
  fi
  if [[ -n "${WATCHER_PID}" ]]; then
    log_info "Stopping watcher (PID ${WATCHER_PID})..."
    kill "${WATCHER_PID}" 2>/dev/null || true
    wait "${WATCHER_PID}" 2>/dev/null || true
  fi
  stop_xctestservice
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --device)
      if [[ $# -lt 2 ]]; then
        log_error "--device requires a value."
        usage
        exit 1
      fi
      DEVICE_ID="$2"
      shift 2
      ;;
    --skip-ai)
      SKIP_AI=true
      shift
      ;;
    --once)
      RUN_ONCE=true
      shift
      ;;
    --poll-interval)
      if [[ $# -lt 2 ]]; then
        log_error "--poll-interval requires a value."
        usage
        exit 1
      fi
      POLL_INTERVAL="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

trap cleanup EXIT INT TERM

mkdir -p "${PROJECT_ROOT}/scratch"

if ! ensure_dependencies; then
  log_error "Dependency check failed. Exiting."
  exit 1
fi

if ! command -v xcodebuild >/dev/null 2>&1; then
  log_error "xcodebuild not found. Install Xcode."
  exit 1
fi

if [[ ! -d "${XCTEST_SERVICE_DIR}" ]]; then
  log_error "XCTestService directory not found: ${XCTEST_SERVICE_DIR}"
  exit 1
fi

if [[ -n "${DEVICE_ID}" ]]; then
  export SIMULATOR_ID_OVERRIDE="${DEVICE_ID}"
  log_info "Target simulator: ${DEVICE_ID} (must be booted)"
else
  log_info "Target: booted simulator"
fi

log_info "Derived data: ${DERIVED_DATA_PATH}"

if [[ "${RUN_ONCE}" == "true" ]]; then
  if ! build_xctestservice; then
    log_error "Build failed. Fix errors and retry."
    exit 1
  fi
  log_info "Run-once mode complete."
  exit 0
fi

kill_previous

PORT=$(detect_port "${PROJECT_ROOT}")
log_info "Using port ${PORT}"

update_mcp_json "${PORT}"
update_codex_toml "${PORT}"

cd "${PROJECT_ROOT}"

start_mcp_server

if [[ "${SKIP_AI}" == "true" ]]; then
  log_info "Hot-reload running."
  log_info "MCP endpoint: http://localhost:${PORT}/auto-mobile/streamable"
  watch_loop "${POLL_INTERVAL}"
else
  start_watcher
  sleep 2
  prompt_ide
fi
